### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by dongqian0206** [dreasysnail/INSET#3]
Hi Yichen,

Thanks for your released source code. 

Would it be also possible to provide the pre-processed datasets for facilitating future research? Looking forward to hearing from you. 

Best,

Dong

**Comment by yichenhuang** [comment]
Hi Dong,

Thanks for your interest in our work. We will release the source code and pre-processed datasets in a week.

Best,
Yichen

**Comment by dongqian0206** [comment]
> Hi Dong,
> 
> Thanks for your interest in our work. We will release the source code and pre-processed datasets in a week.
> 
> Best,
> Yichen

Good to hear that.
